# Generated by Django 5.2.2 on 2025-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('time_limit', models.IntegerField(help_text='Time limit in seconds')),
                ('test_cases', models.JSONField(help_text='List of test cases with inputs and expected outputs')),
                ('sample_input', models.TextField(help_text='Sample input for the problem')),
                ('sample_output', models.TextField(help_text='Sample output for the problem')),
                ('solution_template', models.TextField(blank=True, help_text='Optional starter code template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
    ]
