# Generated by Django 5.2.2 on 2025-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_file',
            field=models.CharField(default='two_sum_test.c', help_text='Name of the test file in problem_tests directory', max_length=200),
            preserve_default=False,
        ),
    ]
